# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 19:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default=datetime.datetime(2016, 6, 5, 19, 18, 49, 21352, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
