# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('armory_app', '0002_post_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='settings.MEDIA_ROOT/avatars/default.jpg', upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_text',
            field=models.TextField(default='Some text here.'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='com_text',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='A title here', max_length=200),
        ),
    ]
