# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory_app', '0003_auto_20160606_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='armory_app.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='com_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='armory_app.Author'),
        ),
    ]
